### ISSUE TITLE
test & data

### ISSUE THREAD

**Issue by mahyarx** [zafercavdar/brainID#1]
Hello, Thanks for sharing knowledge 
could you please add some sample test and data please , i've tried to add my own samples, seems columns are not fit or maybe add some description please how to use it.
best regards

**Comment by zafercavdar** [comment]
@mahyarx You need to rename the sample csv file to `$SUBJECT_$STATE_$DATE.csv`, for example: "MAHYAR_ATTENTIONTEST_20190506.csv"
